saq/__init__.py
saq/worker.py
tests/test_worker.py

Call after_process so any clean up can still occur even if the job raised an exception.

Always call after_process

---

.gitignore
saq/queue.py

This is failing on other PRs before a new version of pylint has been released.
We can consider pinning the pylint version. But this wasn't that painful 🤷 
@tobymao

Fix lint errors for pylint 2.12.2 -> 2.13.2

---

saq/worker.py
tests/test_worker.py

This lets users define synchronous job functions.
This is essentially the same thing that FastAPI does: https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L152
This isn't strictly required, as it's easy to workaround for users. But IMO, this is a nice framework convenience.
@tobymao

Support synchronous job functions

---

examples/map.py
saq/__main__.py
saq/queue.py
saq/static/app.js
saq/web.py
saq/worker.py
tests/test_queue.py
tests/test_web.py

This is the result of our discussion on https://github.com/tobymao/saq/pull/13
Before this PR, a web UI instance monitors all queues in the same Redis database. This had some fundamental issues.
This change makes it so a web UI instance only monitors the queue for the worker it's attached to.
If users want to monitor multiple queues in the web UI, they can append `--additional-web-settings` parameters to the `saq` command.
@tobymao

Monitor multiple queues in the Web UI

---

examples/propagation.py
saq/job.py
saq/queue.py
saq/worker.py
tests/test_job.py
tests/test_worker.py

This should be able to handle most cases of context propagation between jobs.
This doesn't have a strong opinion on _what_ context is propagated and instead just allows for arbitrary metadata. This should work for OpenTracing, DataDog tracing, asgi-correlation-id, etc.
@tobymao 
@sondrelg

Better support for context propagation

---

saq/job.py
tests/test_job.py

@barakalon wasn't that hard to continue pruning results, default for the dataclass just returns MISSING_VALUE which is fine.

continue to prune dict

---

saq/queue.py

@tobymao 
@barakalon 
While using `queue.apply()`, I would sometimes get a Redis ConnectionError instead of the expected asyncio TimeoutError. It looks like the listen task in map() is wrapped in an asyncio.wait_for(), but listen() already uses an asyncio.wait_for() of its own. Since they both have the same timeout, the outer wait_for()'s cancellation can sometimes interfere with listen()'s wait_for's cancellation if it's taking some time to clean up, e.g. close and clean up the redis connection. This PR passes `None` to listen()'s timeout and lets `queue.map()` handle timing out the listen() task.

Fix bug with queue map timeouts

---

saq/job.py
saq/queue.py
tests/test_queue.py

Currently, the information attached to a job that has been processed are necessarily stored back in redis. In some cases, this is not needed, and unwanted.
I added a way for users to disable this feature by making the ttl have three states:
- positive (e.g. 600): the job is saved back to redis with an expiry after processing
- neutral (e.g. 0): the job is saved back to redis without expiry
- negative (e.g. -1): the job is not saved back to redis
I thought about using positive, None, and 0, but decided to stay with one type, not sure what's best honestly.

Allow users to expire, keep, or disable storage of job information

---

README.md

Update readme's start-worker command to avoid [ModuleNotFoundError](https://github.com/tobymao/saq/issues/26)

update readme start-worker command

---

.pylintrc
tests/test_web.py

- closes the aiohttp session after each test
- removes 'no-self-use' from .pylintrc disable= section (useless-option-value)

Fixes warnings from running `run_checks.sh`.

---

.github/workflows/python-ci.yml
MANIFEST.in
mypy.ini
run_checks.sh
saq/__init__.py
saq/__main__.py
saq/compat.py
saq/job.py
saq/queue.py
saq/types.py
saq/utils.py
saq/web.py
saq/worker.py
setup.py
tests/helpers.py
tests/test_job.py
tests/test_queue.py
tests/test_utils.py
tests/test_web.py
tests/test_worker.py

- Used MonkeyType and the test suite to generate  a set of annotations
- Added mypy and necessary stub dependencies to dev extras
- Adds types.py module for type definitions/aliases etc
- Adds py.typed
- Removes support for 3.7
Related to #39

Feat: Adds type annotations

---

saq/queue.py

Broaden typing for `job_keys` param to `Queue.listen()`.

---

saq/worker.py

This fixes a bug where the worker didn't pick up the correct queue when starting causing it to always use `default` on localhost

Fix worker queue settings

---

saq/job.py

Docstring names property as `results` whereas the actual property name is `result`.

Fix Job.result documented property name

---

saq/worker.py

This allows subsequent signals to propagate after the shutdown is triggered. Useful when debugging since you might have some other tasks that didn't finish you want to stop (read spam CTRL-C 😄), without this patch only way to stop the python program is to send a SIGKILL

Clean up signal handlers after shutdown event is triggered

---

saq/queue.py
tests/test_queue.py

Currently SAQ uses first in last out by default. 
This can create problems if lots of new jobs are being enqueued. Leaving this as the current default behavior to not surprise anyone, but creating an option to change it.

Add option to have SAQ use fifo instead of filo

---

saq/__main__.py

If you are busy developing and didn't do a `pip install -e .` yet, `saq foo.settings` is not equivalent to `python -m saq foo.settings` due to the prior only having access to installed modules.
This adds the current path to the module path so that it will work for both cases.

Includes the current path as a module path to allow importlib finding in-development modules

---

saq/queue.py

This is because the web interface will hide jobs that are rescheduled. 
I replaced queued with incomplete because it looks like incomplete is a superset of it.

Fetch outstanding jobs from incomplete namespace instead of queued.

---

CHANGELOG.md
setup.py

Hi, thanks for releasing a new version, but it seems that the saq.web pacakges are not included. (my bad, I didn't verify that setup.py didn't use `find_packages()`)
I also updated the CHANGELOG assuming the next release should be called v0.11.2

Added package saq.web to build

---

saq/__main__.py

This confuses things, and at first I through there was no SIGINT handling, but it's there and it works.
It just prints spurious things if multiprocessing is used.

Silence SIGINT causing tracebacks of different process dumping to stderr

---

setup.py
tests/test_queue.py

Adding strategic sleep gives async process time to catch up.
No longer failing on redis==5.0
Also fixes flaky tests on redis<5

Support redis==5.0

---

saq/__main__.py
saq/job.py
saq/queue.py
saq/worker.py

I prefer a modicum of logging to simplify diagnostics, but not too much.
* Default loglevel of `ERROR` was too restrictive as warnings won't get reported. I changed the default loglevel to include `WARNING`.
* The Worker would not log when it started up, so I added an `INFO` for that, it includes logging the `Queue` config being used for easy identification of the worker.
* The Worker now logs the configured functions as `DEBUG`.
* The `INFO` loglevel would dump the entire payload and extra data for each job which would fill up the logs with more data, this was quite a jump from no logs at all for job processing. I split it up so that if loglevel is `INFO` it will emit an abridged version of the Job, and if loglevel is `DEBUG` it will emit the full version. (I'm not 100% happy about this, …

Logging verbosity balancing.

---

saq/queue.py

Use redis's aclose() method if available otherwise fallback to close().
Note: Follow-up to [PR #102](https://github.com/tobymao/saq/pull/102)

Update queue.py to support redis >= 5.* aclose method.

---

README.md
saq/worker.py
tests/test_settings_import.py
tests/test_worker.py

Allow the settings objects imported during `saq.worker.start()` to be callable. This makes it possible to eliminate import-time side effects, especially if creating the settings objects is more involved.
In my case, I'm leveraging multiple queues and using a dependency injection framework to wire the `saq.Queue`s a certain way. While I could sequester the settings objects to their separate modules, I find it more convenient to keep them together.
Let me know if this idea is OK and thank you for this neat little framework!

Support settings factories

---

saq/__init__.py
saq/job.py
saq/queue.py
saq/types.py
saq/utils.py
saq/web/starlette.py
saq/worker.py
tests/test_queue.py

Old code doesn't allow colons in job keys

fix: allow colons in job key

---

saq/queue.py

Aws elasticache redis doesnt vibe with current version of SAQ

Handle redis version being a float

---

setup.py

Fixes #137 
The queue package was not being included when building the wheel. This PR now includes it.

Include queue package when building

---

README.md
saq/job.py
tests/test_worker.py

Fix a bug where cronjob creation could not accept a kwargs parameter as described in the documentation

Fix cronjob inability to pass kwargs to the function

---

saq/queue/postgres.py

Right now, timeout of 0 times out immediately, which is wrong.

Fix: Listen forever if timeout param is 0 (postgres)

---

saq/queue/base.py
saq/queue/postgres.py
saq/utils.py
saq/worker.py
tests/helpers.py
tests/test_queue.py
tests/test_worker.py

This PR introduces queue specific upkeep tasks. For the Postgres queue, this helps decouple opening the queue's connection pool and various upkeep tasks like the dequeue timer and enqueue listener.

Chore: Introduce queue upkeep

---

setup.py

Some features, like AsyncConnection.cancel_safe(), is only available since psycopg v3.2.0.

Fix: Set psycopg minimum version to 3.2.0

---

saq/queue/postgres.py
tests/test_queue.py

Jobs should not have an expiration while it is aborting. Redis has a TTL on abort_id, but Postgres doesn't use abort_id. Postgres won't re-enqueue an aborting job by checking the job's status.

Fix: Do not expire jobs when aborting

---

saq/queue/postgres.py
saq/queue/redis.py

Some job functions simply pass arguments through to their corresponding queue functions.

Chore: Replace job calls in queue with self calls

---

saq/queue/base.py
saq/queue/postgres.py
tests/test_queue.py

If a job hasn't been dequeued yet and it is aborted, its status should be updated to `aborted`.

Fix: Handle aborting a job before it has started processing in Postgres

---

saq/queue/postgres.py
tests/test_queue.py

Still need to figure out sweep advisory lock key per queue.

Fix: A queue's sweeper should only sweep jobs that belong to it

---

saq/queue/postgres.py
tests/test_queue.py

the sweeper atomically changes the job table state to be active, when a job gets processed, at that point it will be updated to active. it won't get swept if there's an advisory lock. if the lock is lost and the job never got picked up, then it will be considered stuck and swept.

fix: postgres sweeping doesn't need to update job state

---

saq/queue/base.py
saq/queue/http.py
saq/queue/postgres.py

This way other threads can schedule Queue's coroutines on the same event loop in which the queue was connected.

Feat: Preserve the event loop in a Queue when connecting

---

saq/queue/base.py
saq/queue/http.py
saq/queue/postgres.py
saq/queue/redis.py
saq/types.py
saq/worker.py
tests/test_http_stats.py
tests/test_queue.py

**FIRST COMMIT**
Currently, stats are written to the store by the Queue class, and before a Queue instance contains a UUID used to identify the worker.
When a Postgres or Redis Queue is created inside a worker, the ID will be unique to that worker, and the stats are stored as expected. In this case, a Queue instance is created with a unique ID wrapped in a Worker class, which then pushes the stats to the store with the ID from that queue instance, which is unique to that worker. 
This is currently not quite the case with HTTP. In an HTTP Proxy scenario, the proxy creates a Queue instance that contains a unique ID for the worker, as is done in the case of Redis and Postgres. When an HTTP worker Queue is created, this instance will contain the unique ID representative of that worker. When, …

fix: http workers pass their own id

---

saq/types.py

```
packages/pydantic/_internal/_generate_schema.py", line 1115, in _typed_dict_schema
raise PydanticUserError(
pydantic.errors.PydanticUserError: Please use `typing_extensions.TypedDict` instead of `typing.TypedDict` on Python < 3.12.
```
Fixes this error when used upstream in pydantic.

feat: allow types to be used upstream in pydantic

---

saq/worker.py
setup.py
tests/test_worker.py

Hi, thanks for this cool project!
I want to use SAQ for a trading app, where taking into account New York time (and DST) is very important. Currently there is no way to do this as far as I can tell, but it's a small change!
I am unfamiliar with `unittest`, so I may need some guidance making sure the tests work correctly here and adding new ones.

add timezone to cron scheduler

---

saq/job.py
saq/worker.py
tests/test_job.py

with the http queue, jobs can be forever stuck in aborting because the server (postgres) continues to hold onto the lock. this makes it so that they will move onto aborted despite the lock. the worker additionally will check for aborted/aborting.

fix: allow aborting jobs to be swept

---

saq/job.py
saq/queue/base.py
saq/queue/http.py
saq/queue/postgres.py
saq/queue/redis.py
saq/worker.py
tests/test_queue.py
tests/test_worker.py

prior to this commit, job.update() would also override status, this is problematic when using update() for heartbeats since it would override an abort. now, a job status only gets updated if status is passed in directly.

fix!: update defaults to not touching status

---

saq/queue/http.py

- allows passing own client session for example where need it to be more dynamic, e.g. load a new auth token on request

feat: allow override of client session

---

saq/queue/postgres_migrations.py
saq/worker.py

These index probably won't be used by the query planner unless the jobs table has hundreds of thousands of rows, but they do significantly speed up the query when there are that many jobs.

Feat: Improve Postgres dequeue performance with additional indexes

---

docs/monitoring.md
examples/monitor_fastapi.py

In general I think it is a good way to include examples from files. This way linters & formatters can help keeping the code up-to date. 
An even better way would be to references examples from tests.

literalinclude monitor_fastapi.py as FastAPI monitor example

---

saq/worker.py

Prior to this PR, if a worker stopped due to an exception then the web app would keep running despite the fact that there are no workers available. This change makes it so that when the worker stops then it emits a sigterm in order to bring down the web app too.

fix: prevent zombie web worker

---

README.md
saq/queue/base.py
tests/test_queue.py

#238 
Also adds a test case for poll_interval.
I'm not sure about the readme changes, but for my use-case (low latency tasks) the `poll_interval` is a crucial part in understanding how the library works and making it respond faster. The mentions of "avoids polling" in the readme were confusing to me as they do not say that it does not apply to the results.

Add poll_interval argument to apply

---

saq/queue/http.py
tests/test_http_retry.py

Adds retry to http calls. An exception is made for dequeue since it is not currently idempotent.

feat: add retry to http calls

---

docs/task.md

This pull request completes the documentation for the "Tasks" section. It replaces the previous TODO and incomplete content with a comprehensive guide that covers:
- The distinction between a Task and a Job.
- Registering tasks with a Worker.
- Enqueueing jobs with various options (retries, timeout, etc.).
- A detailed explanation of the Context object.
- Using apply() to fetch results.
- Defining recurring Cron Jobs.

docs: Complete and expand documentation for Tasks section

---

saq/worker.py
tests/test_worker.py

Moves `shutdown` callback execution to after `worker.stop()`
`shutdown` callbacks are most often used to cleanup shared resources used by tasks, example being database connections, pools etc. Because these callbacks were executed before calling on `worker.stop()` we were encountering an inconsistent state failures from active tasks trying to use resources cleaned up by our `shutdown` callback.

fix: Allow tasks to stop before cleanup
