saq/job.py
saq/queue.py
saq/utils.py
saq/worker.py
tests/test_queue.py
tests/test_worker.py

instead switch to polling for aborts and have users generate heartbeats
explicitly

the previous implementation of monitor was prone to race conditions

---

saq/__init__.py
saq/web.py

Health check endpoint performs a check similar to the `async_check_health` function in worker.py.
> https://github.com/tobymao/saq/blob/b05d201e5f41ddef66f409233538c4ccf1e470ea/saq/worker.py#L277

Add health check endpoint to web application

---

.gitignore
README.md
saq/job.py

This is a handful of minor fixups I made while testing out saq.
More substantial proposals to come.

Minor fix-ups

---

saq/__main__.py

Whoops, I forgot to update this in my PR

Fix CLI help text

---

saq/__main__.py
saq/worker.py

One more tweak here. 
"extra" is five less characters than "additional". 
This is why I get paid the big bucks.

Rename additional to extra

---

saq/job.py
saq/queue.py
saq/web.py
setup.py
tests/test_queue.py
tests/test_worker.py

cron jobs may not be unique if they have the same name but run in different queues

Use queue name in the job key

---

saq/worker.py

This PR tweaks the way errors are logged, to include more metadata.
I didn't spend a lot of time crafting the logger messages, so suggestions for better ones are very welcome 🙂 
We use [Sentry](sentry.io) for errors, and `saq` currently logs job exceptions in a way that's slightly too generic for Sentry. Since the plaintext dump of a traceback is logged without any extra information, all errors raised by `saq` are bundled together. Moreover, there is a size limit to log message length in Sentry, so we're not even receiving the full tracebacks (see screenshot at the bottom of the comment below).
Using `logger.exception` or `logger.error(..., exc_info=True)` (they're the same thing), we're able to get proper Sentry events, containing the complete traceback plus "breadcrumbs"

fix: Replace exception logger function with logger.exception

---

docs/conf.py
docs/index.md
docs/worker.md
saq/job.py
saq/queue.py
saq/types.py
saq/utils.py
saq/web/aiohttp.py
saq/web/starlette.py
saq/worker.py
setup.cfg

* Autodoc now uses the typehints, resulting in less duplication and better inter-doc linking.
* Added docstrings to all attributes/methods that I think should be public.
* Disabled autoapi generating document for undocumented members to make the api docs more concise.
* Improved front-page cards to have better contrast for better readability

AutoAPI docs basically complete now.

---

saq/job.py
saq/worker.py

Previously health check function only checks that queue stored in redis and not that the worker is online

Actually check for online workers on healthcheck

---

README.md

Making this method easier to find

Add Queue.map to the README

---

saq/queue.py

add lock when creating pubsub daemon (#119)

---

saq/types.py
saq/worker.py
tests/test_worker.py

Fixes https://github.com/tobymao/saq/issues/122

fix: update abort status before after_process

---

.github/workflows/python-ci.yml
Makefile
benchmarks/README.md
benchmarks/simple.py
saq/job.py
saq/queue/base.py
saq/queue/postgres.py
saq/queue/postgres_ddl.py
saq/queue/redis.py
saq/types.py
saq/worker.py
tests/helpers.py
tests/test_job.py
tests/test_queue.py
tests/test_worker.py
tests/web/test_aiohttp.py

This PR introduces a Postgres-backed queue. Still need to add tests and implement several missing features like info, stats, schedule, sweep, etc.

Introduce Postgres queue

---

saq/queue/postgres.py

This prevents warnings like the one below during health checks (even if the check succeeds):
```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-35' coro=<PostgresQueue.listen_for_enqueues() running at saq/queue/postgres.py:540> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

Wait for Postgres queue tasks to finish cancelling when disconnecting

---

saq/queue/postgres.py
saq/queue/postgres_ddl.py
tests/test_queue.py
tests/test_worker.py

Fix the Postgres queue's sweep to match the Redis queue

Fix!: Postgres queue sweep

---

saq/queue/postgres.py
tests/test_queue.py

Fixes #162
A bad queue.connection will cause the worker to hang. This PR checks queue.connection when it is about to be used and replaces it with a new one from the pool if it's bad. There is a caveat regarding the active jobs of the worker using the queue. The worker no longer holds the advisory locks for those active jobs so they will be swept.

Fix: Recover from bad Postgres connection

---

saq/web/starlette.py

fix: lint path handling

---

saq/queue/http.py
tests/test_worker.py

- add test case to make sure it works
- fix typo

fix: info queue test case added

---

saq/web/static/app.js

fix: fix web stats

---

saq/errors.py
saq/queue/base.py
tests/helpers.py
tests/test_queue.py
tests/test_worker.py

raise an error if from_url argument misses the scheme

---

saq/queue/postgres.py

This change is meant to improve the API of SAQ queues for usage where you already have a Postgres connection pool and hand it to SAQ. 
The goal is to make the management of the Postgres pool completely the user's responsibility in the case where you hand saq a pool. So this change makes SAQ not 
- open
- resize
- close
the pool in the case where SAQ is passed a pool.

feat: allow the user of the queue to be in charge of connection

---

Makefile
saq/job.py
saq/queue/base.py
saq/queue/postgres.py
saq/queue/redis.py
saq/utils.py
tests/test_job.py
tests/test_queue.py

improves performance and removes potential deadlocks

fix: force autocommit

---

saq/queue/postgres.py

Allows users to opt-in to this behavior even if they are providing a pool.

feat: add manage pool lifecycle

---

README.md

Added a DBHelper class so the examples can be run as is.

Complete example in README.md

---

saq/queue/postgres.py

If the psycopg pool closes the connection then it sets the pool to None: https://github.com/psycopg/psycopg/blob/90e5e5901fccb9faaa9add9a8c4610c5a476fa1b/psycopg_pool/psycopg_pool/null_pool_async.py#L124
If this closing happens outside of SAQ itself it means we can have a cached connection which is closed. The logic reads like this would be ok since it checks the connection first but after that it tries to put the connection back but you can't put a connection back into a pool that isn't associated with that pool and its no longer associated with the pool since it was closed. 
Therefore this PR checks if the connection has been dissociated with a pool and if so it no longer uses that connection. It also confirms that the connection has been closed by calling close on it. the close method …

fix: handle case where connection pool closes connection
